//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderEntities : DbContext
    {
        public OrderEntities()
            : base("name=OrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<T_Account> T_Account { get; set; }
        public virtual DbSet<T_AccountRate> T_AccountRate { get; set; }
        public virtual DbSet<T_FaceValue> T_FaceValue { get; set; }
        public virtual DbSet<T_Game> T_Game { get; set; }
        public virtual DbSet<T_Module> T_Module { get; set; }
        public virtual DbSet<T_Order_Base> T_Order_Base { get; set; }
        public virtual DbSet<T_Order_Detail> T_Order_Detail { get; set; }
        public virtual DbSet<T_OrderStateHistory> T_OrderStateHistory { get; set; }
        public virtual DbSet<T_Player> T_Player { get; set; }
        public virtual DbSet<T_Product> T_Product { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_UserModule> T_UserModule { get; set; }
        public virtual DbSet<T_Balance> T_Balance { get; set; }
    }
}
