//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Account
    {
        public long Id { get; set; }
        public string AppId { get; set; }
        public decimal Balance { get; set; }
        public int State { get; set; }
        public string Comments { get; set; }
    }
}
