//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Game
    {
        public long id { get; set; }
        public string name { get; set; }
        public System.DateTime createtime { get; set; }
        public string CreateUser { get; set; }
        public string comment { get; set; }
    }
}
