//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Module
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public string Url { get; set; }
        public int ParentID { get; set; }
        public int SeqNo { get; set; }
        public string Icon { get; set; }
        public bool IsDisplay { get; set; }
    }
}
