//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order_Detail
    {
        public long ID { get; set; }
        public string ProductName { get; set; }
        public long GameID { get; set; }
        public int Numbers { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime PayTime { get; set; }
        public string PayAccount { get; set; }
        public Nullable<long> GoldAccount { get; set; }
        public string PayDeviceAccount { get; set; }
        public Nullable<long> Pay4PlayerId { get; set; }
    }
}
