//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order_Base
    {
        public long ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public decimal TotalPrice { get; set; }
        public int StateID { get; set; }
        public string Source { get; set; }
        public string PayerName { get; set; }
        public string Comments { get; set; }
        public string TransferAccountNumber { get; set; }
        public Nullable<decimal> TransferredAmount { get; set; }
        public Nullable<System.DateTime> TransferAccountTime { get; set; }
        public string TransferMethod { get; set; }
        public string BeneficiaryAccountNo { get; set; }
        public string CreaterUser { get; set; }
    }
}
