//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Player
    {
        public long Id { get; set; }
        public string PlayerName { get; set; }
        public string RoleName { get; set; }
        public int Rank { get; set; }
        public long PreviousGoldAccount { get; set; }
        public long laterGoldAccount { get; set; }
        public decimal TradeTax { get; set; }
        public decimal ProductTax { get; set; }
        public string EquipmentName { get; set; }
    }
}
