//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThrFrd.GameTrans.Admin.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long GameID { get; set; }
        public string Category { get; set; }
        public string Client { get; set; }
        public string Domain { get; set; }
        public long Amount { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
    }
}
